name: Publish Docker Images

on:
  push:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: nodejs
            version: "18"
            base_arg: NODE_VERSION
          - language: nodejs
            version: "19"
            base_arg: NODE_VERSION
          - language: nodejs
            version: "20"
            base_arg: NODE_VERSION
          - language: nodejs
            version: "21"
            base_arg: NODE_VERSION
          - language: nodejs
            version: "22"
            base_arg: NODE_VERSION
          - language: nodejs
            version: "23"
            base_arg: NODE_VERSION
          - language: nodejs
            version: "24"
            base_arg: NODE_VERSION
          - language: nodejs
            version: "25"
            base_arg: NODE_VERSION
          - language: python
            version: "3.8"
            base_arg: PYTHON_VERSION
          - language: python
            version: "3.9"
            base_arg: PYTHON_VERSION
          - language: python
            version: "3.10"
            base_arg: PYTHON_VERSION
          - language: python
            version: "3.11"
            base_arg: PYTHON_VERSION
          - language: python
            version: "3.12"
            base_arg: PYTHON_VERSION
          - language: golang
            version: "1.18"
            base_arg: GOLANG_VERSION
          - language: golang
            version: "1.19"
            base_arg: GOLANG_VERSION
          - language: golang
            version: "1.20"
            base_arg: GOLANG_VERSION
          - language: golang
            version: "1.21"
            base_arg: GOLANG_VERSION
          - language: golang
            version: "1.22"
            base_arg: GOLANG_VERSION
          - language: golang
            version: "1.23"
            base_arg: GOLANG_VERSION

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.language }}
          tags: |
            type=raw,value=${{ matrix.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.language }}
          file: docker/${{ matrix.language }}/Dockerfile
          push: true
          build-args: |
            ${{ matrix.base_arg }}=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
